[package]
name = "rbac-types"
version = "0.2.14-dev"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
lava-ids = { path = "../ids" }
dashboard = { path = "../dashboard" }

governance = { path = "../../core/governance" }
core-user = { path = "../../core/user" }
audit = { path = "../../lib/audit" }
authz = { path = "../../lib/authz" }

strum = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
async-graphql = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
