[package]
name = "rbac-types"
version = "0.2.3-dev"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
governance = { path = "../../core/governance" }
core-user = { path = "../../core/user" }
shared-primitives = { path = "../../core/shared-primitives" }
audit = { path = "../../lib/audit" }

strum = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
async-graphql = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
