services:
  core-pg:
    image: postgres:15.5
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pg
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 1s
      retries: 20
  cala-pg:
    image: postgres:15.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=pg
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 1s
      retries: 20
  cala:
    image: gcr.io/galoy-org/cala-enterprise:edge
    ports:
      - "2252:2252"
    volumes:
      - ./dev/cala.yml:/cala.yml
    environment:
      - PG_CON=postgresql://user:password@cala-pg:5432/pg
      - CALA_CONFIG=/cala.yml
      - BFX_LOCAL_TESTING=true
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-agent:4317
    depends_on:
      - cala-pg
      - otel-agent
  otel-agent:
    ports:
      - "4317:4317" # OpenTelemetry receiver
    image: otel/opentelemetry-collector-contrib:0.57.2
    command: ["--config=/etc/otel-agent-config.yaml"]
    environment:
      - HONEYCOMB_DATASET=${HONEYCOMB_DATASET}
      - HONEYCOMB_API_KEY=${HONEYCOMB_API_KEY}
    volumes:
      - ./dev/otel-agent-config.yaml:/etc/otel-agent-config.yaml
  kratos:
    image: oryd/kratos:v1.2.0
    extra_hosts:
      - "dockerhost-alias:host-gateway"
    ports:
      - "4433:4433" #! public
      - "4434:4434" #! admin
    entrypoint: sh -c
    command: '"kratos migrate sql up -y -e && kratos serve -c /home/ory/kratos.yml --watch-courier --sqa-opt-out"'
    environment:
      DSN: postgres://dbuser:secret@kratos-pg:5432/default?sslmode=disable
    links:
      - kratos-pg:kratos-pg
      - mailhog:mailhog
    volumes:
      - ./dev/ory:/home/ory
  kratos-pg:
    image: postgres:15.5
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=default
  next-auth-pg:
    image: postgres:15.5
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=default
  oathkeeper:
    image: oryd/oathkeeper:v0.40.7-distroless
    extra_hosts:
      - "dockerhost-alias:host-gateway"
    ports:
      - 4455:4455
      - 4456:4456
    command: serve -c /home/ory/oathkeeper.yml --sqa-opt-out
    volumes:
      - ./dev/ory:/home/ory
    depends_on:
      - kratos
      - otel-agent
  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"
