[package]
name = "lava-cli"
version = "0.2.1-dev"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
lava-app = { path = "../app" }
lava-server = { path = "../server" }

tracing-utils = { path = "../../lib/tracing-utils", features = ["http"] }


anyhow = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
sqlx = { workspace = true }
