[package]
name = "core-money"
version = "0.3.161-dev"
edition = "2021"

[dependencies]

serde = { workspace = true }
thiserror = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
async-graphql = { workspace = true }
