[package]
name = "rbac-types"
version = "0.3.554-dev"
license = "FSL-1.1-ALv2"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
lana-ids = { path = "../ids" }
dashboard = { path = "../dashboard" }

governance = { path = "../../core/governance" }
core-access = { path = "../../core/access" }
core-customer = { path = "../../core/customer" }
core-credit = { path = "../../core/credit" }
deposit = { path = "../../core/deposit" }
core-accounting = { path = "../../core/accounting" }

audit = { path = "../../lib/audit" }
authz = { path = "../../lib/authz" }

strum = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
async-graphql = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
