[package]
name = "rbac-types"
version = "0.3.33-dev"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
lana-ids = { path = "../ids" }
dashboard = { path = "../dashboard" }

governance = { path = "../../core/governance" }
core-user = { path = "../../core/user" }
core-customer = { path = "../../core/customer" }
chart-of-accounts = { path = "../../core/chart-of-accounts" }
deposit = { path = "../../core/deposit" }
audit = { path = "../../lib/audit" }
authz = { path = "../../lib/authz" }

strum = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
async-graphql = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
