[package]
name = "user-onboarding"
version = "0.3.161-dev"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
lana-events = { path = "../events" }
core-user = { path = "../../core/user" }

outbox = { path = "../../lib/outbox" }
job = { path = "../../lib/job" }
audit = { path = "../../lib/audit" }
kratos-admin = { path = "../../lib/kratos-admin" }

sim-time = { workspace = true, optional = true }
es-entity = { workspace = true, features = ["graphql"] }

uuid = { workspace = true }
strum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
async-graphql = { workspace = true }
ory-kratos-client = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
