[package]
name = "lava-ids"
version = "0.2.14-dev"
edition = "2021"

[features]

default = ["graphql"]
graphql = []

[dependencies]
governance = { path = "../../core/governance", features = ["graphql"] }

job = { path = "../../lib/job" }
es-entity = { path = "../../lib/es-entity", features = ["graphql"] }

sqlx = { workspace = true }
serde = { workspace = true }
