#@data/values
---
git_uri: git@github.com:GaloyMoney/lana-bank.git
git_branch: main
github_private_key: ((github.private_key))
github_token: ((github.api_token))
github_app_id: ((github.github_app_id))
github_app_private_key: ((github.github_app_private_key))

git_charts_uri: git@github.com:GaloyMoney/galoy-private-charts.git
git_charts_branch: main
git_charts_bot_branch: bot-bump-lana-bank-image

gar_registry: us.gcr.io/galoyorg
gar_registry_user: ((gar-creds.username))
gar_registry_password: ((gar-creds.password))

docker_registry_user: ((docker-creds.username))
docker_registry_password: ((docker-creds.password))

cachix_auth_token: ((cachix-token.token))

git_version_branch: version
gh_org: GaloyMoney
gh_repository: lana-bank

folder_registry_image: lana-bank
folder_registry_image_static: lana-bank-static
