[package]
name = "lava-events"
version = "0.2.3-dev"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
governance = { path = "../../core/governance" }
shared-primitives = { path = "../../core/shared-primitives" }
outbox = { path = "../../lib/outbox" }

serde = { workspace = true }
