[package]
name = "lava-events"
version = "0.2.14-dev"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
governance = { path = "../../core/governance" }
core-user = { path = "../../core/user" }
outbox = { path = "../../lib/outbox" }

chrono = { workspace = true }
serde = { workspace = true }
