[package]
name = "lana-events"
version = "0.3.114-dev"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
governance = { path = "../../core/governance" }
core-user = { path = "../../core/user" }
core-customer = { path = "../../core/customer" }
core-credit = { path = "../../core/credit" }
deposit = { path = "../../core/deposit" }
outbox = { path = "../../lib/outbox" }

serde = { workspace = true }
