[package]
name = "lana-events"
version = "0.3.46-dev"
edition = "2021"

[features]

fail-on-warnings = []

[dependencies]
governance = { path = "../../core/governance" }
core-user = { path = "../../core/user" }
core-customer = { path = "../../core/customer" }
core-money = { path = "../../core/money" }
deposit = { path = "../../core/deposit" }
outbox = { path = "../../lib/outbox" }
lana-ids = { path = "../ids" }

chrono = { workspace = true }
serde = { workspace = true }
