name: "Bats tests"

on:
  pull_request:
    branches:
      - main
      - "feature/**"

jobs:
  bats-tests:
    name: End to End Bats Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-nix
        with:
          cachix_auth_token: ${{ secrets.CACHIX_AUTH_TOKEN_LANA_CI }}
          google_credentials: ${{ secrets.GOOGLE_CREDENTIALS }}
      - uses: ./.github/actions/cache-rust 
      - name: Run e2e tests
        run: nix develop -c make e2e
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          TF_VAR_sa_creds: ${{ secrets.GOOGLE_SA_BASE64 }}
          SA_CREDS_BASE64: ${{ secrets.GOOGLE_SA_BASE64 }}
          SUMSUB_KEY: ${{ secrets.SUMSUB_KEY }}
          SUMSUB_SECRET: ${{ secrets.SUMSUB_SECRET }}
          TF_VAR_name_prefix: "gha"
      - name: Rename Tilt log
        if: always()
        run: mv .e2e-logs e2e-logs
      - name: Upload Tilt log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Tilt log
          path: |
            e2e-logs
            *.e2e-logs
